name: Deploy release from source
on:
  repository_dispatch:
    types: [deploy_release]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Configure bot identity
        run: |
          git config user.name "ConcatenateLineMobile[bot]"
          git config user.email "mobile-bot@concatenateline.dev"

      - name: Create tag
        run: |
          git tag -a ${{ github.event.client_payload.tag_name }} -m "Release ${{ github.event.client_payload.tag_name }}"
          git push origin ${{ github.event.client_payload.tag_name }}

      - name: Download artifact from source run
        env:
          OWNER: ${{ github.event.client_payload.source_owner }}
          REPO: ${{ github.event.client_payload.source_repo }}
          RUN_ID: ${{ github.event.client_payload.run_id }}
          GH_TOKEN: ${{ secrets.SOURCE_APP_READ_TOKEN }} # fine-grained PAT with Actions: read on source repo
          URL: ${{ github.event.client_payload.url }}
          TAG: ${{ github.event.client_payload.tag_name }}
          CHANGELOG: ${{ github.event.client_payload.changelog }}
        run: |
           curl -Lo raffle-studio-${{ env.TAG }}.apk ${{ env.URL }}

           # Create release notes file
           echo ${{ env.CHANGELOG }} > CHANGELOG.md

           # finalize
           echo "âœ… Success! APK downloaded and release notes created"

      - name: Build release
        run: echo ${{ github.sha }} > Release-${{ github.event.client_payload.tag_name }}.txt
      
      - name: Test release
        run: cat Release-${{ github.event.client_payload.tag_name }}.txt
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.client_payload.tag_name }}
          body: ${{ github.event.client_payload.changelog }}
          files: |
            Release-${{ github.event.client_payload.tag_name }}.txt
            raffle-studio-${{ github.event.client_payload.tag_name }}.apk
            CHANGELOG.md
